name: fleet
packages:
  - packages/fleet
  - packages/fleet/example
  - packages/fleet_imports
repository: https://github.com/blaugold/fleet

ide:
  intellij: false

command:
  version:
    linkToCommits: true
    branch: main
    workspaceChangelog: true

scripts:
  format:
    run: daco format .

  format:check:
    run: daco format --set-exit-if-changed .

  analyze:
    exec: dart analyze --fatal-infos

  analyze:doc_comments:
    exec: daco analyze --fatal-infos

  test:unit:
    exec: flutter test
    packageFilters:
      dirExists: test

  presubmit:
    run: |
      melos format:check && \
      melos analyze && \
      melos analyze:doc_comments && \
      melos test:unit
