name: fleet
packages:
  - packages/**
repository: https://github.com/blaugold/fleet

ide:
  intellij: false

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    linkToCommits: true
    branch: main
    workspaceChangelog: true

scripts:
  format:
    run: daco format .

  format:check:
    run: daco format --set-exit-if-changed .

  analyze:
    exec: dart analyze --fatal-infos

  analyze:doc_comments:
    exec: daco analyze --fatal-infos

  check_generated_code:
    exec: ../../tool/check_generated_code.sh
    select-package:
      scope:
        - fleet_view

  test:unit:
    exec: flutter test
    select-package:
      dir-exists: test

  presubmit:
    run: |
      melos format:check --no-select && \
      melos analyze --no-select  && \
      melos analyze:doc_comments --no-select && \
      melos check_generated_code --no-select && \
      melos test:unit --no-select
