name: fleet_imports
description:
  Alternative imports for Flutter libraries, that substitute widgets for which
  Fleet provides drop-in replacements.
version: 0.1.1
issue_tracker: https://github.com/blaugold/fleet/issues
homepage: https://github.com/blaugold/fleet/tree/main/packages/fleet_imports
repository: https://github.com/blaugold/fleet
funding:
  - https://github.com/sponsors/blaugold

environment:
  sdk: '^3.0.0'
  flutter: '>=3.10.0'

dependencies:
  fleet: ^0.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  code_builder: ^4.5.0
