name: fleet_example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fleet: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: any
  fleet_generator: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
