name: fleet_view
version: 0.0.0
issue_tracker: https://github.com/blaugold/fleet/issues
homepage: https://github.com/blaugold/fleet/tree/main/packages/fleet_view
repository: https://github.com/blaugold/fleet
funding:
  - https://github.com/sponsors/blaugold

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  fleet: ^0.2.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  fleet_generator: any
  flutter_test:
    sdk: flutter
