name: fleet_generator
version: 0.0.0
issue_tracker: https://github.com/blaugold/fleet/issues
homepage: https://github.com/blaugold/fleet/tree/main/packages/fleet_generator
repository: https://github.com/blaugold/fleet
funding:
  - https://github.com/sponsors/blaugold

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  fleet_view: any
  flutter:
    sdk: flutter
  meta: ^1.7.0
  source_gen: ^1.2.2
