name: animated_value
description:
  State-based animation framework, which makes animating as easy as setting a
  new value.
version: 0.0.0
issue_tracker: https://github.com/blaugold/animated_value/issues
homepage: https://github.com/blaugold/animated_value/tree/main/packages/animated_value
repository: https://github.com/blaugold/animated_value
funding:
  - https://github.com/sponsors/blaugold

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
