name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Install Daco
        run: dart pub global activate daco

      - name: Check formatting
        run: melos format:check

      - name: Analyze
        run: melos analyze

      - name: Analyze doc comments
        run: melos analyze:doc_comments

      - name: Test
        run: melos test:unit

