name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Melos
        run: dart pub global activate melos 2.6.0

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Install Daco
        run: dart pub global activate daco 0.2.3+2

      - name: Check formatting
        run: melos format:check --no-select

      - name: Analyze
        run: melos analyze --no-select

      - name: Analyze doc comments
        run: melos analyze:doc_comments --no-select

      - name: Check generated code
        run: melos check_generated_code --no-select

      - name: Test
        run: melos test:unit --no-select
